language: go
go:
- 1.10.x
env:
  global:
  - SSH_KEY="travis_key"
  - GIT_NAME="admin"
  - GIT_EMAIL="admin@ladsmechanical.com"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="master"
before_install:
- openssl aes-256-cbc -K $encrypted_0e578b247fcc_key -iv $encrypted_0e578b247fcc_iv
  -in travis_key.enc -out travis_key -d
before_script:
- go get -u -v github.com/spf13/hugo
script:
- hugo
after_success:
- echo "ladsmechanical.com" > ./public/CNAME
- cp README.md ./public/
- chmod +x ./deploy.sh
- "./deploy.sh"

